numerology/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('superadmin/', admin.site.urls),

    path("api/v1/", include("api.urls")),
    path('', include("website.urls")),
    path('customadmin/', include("customadmin.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/customadmin/models.py
from django.db import models

# Create your models here.

app/customadmin/models/cart.py
from django.db import models
from django.utils.translation import gettext as _
from numerology.models import ActivityTracking


class ProductCart(ActivityTracking):
    user = models.ForeignKey("User", on_delete=models.CASCADE)
    product = models.ForeignKey("customadmin.ShopProduct", on_delete=models.CASCADE)
    quantity = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return f"{self.user.email}"

    class Meta:
        verbose_name = "Product Cart"
        verbose_name_plural = "Product Cart"
        ordering = ["-created_at"]


class ServiceCart(ActivityTracking):
    SERVICE_CHOICE = (
        ('Local', 'Local'),
        ('Overseas', 'Overseas'),
    )

    user = models.ForeignKey("User", on_delete=models.CASCADE)
    service = models.ForeignKey("customadmin.Service", on_delete=models.CASCADE)
    service_date = models.DateField(blank=True, null=True)
    service_time = models.TimeField(blank=True, null=True)
    service_type = models.CharField(max_length=100, blank=True, null=True, default='', choices = SERVICE_CHOICE)

    def __str__(self):
        return f"{self.user.email}"

    class Meta:
        verbose_name = "Service Cart"
        verbose_name_plural = "Service Cart"
        ordering = ["-created_at"]

app/customadmin/models/users.py
import uuid
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.contrib.auth.models import BaseUserManager
from django.utils.translation import gettext as _
from numerology.models import ActivityTracking
# Create your models here.


class AccountManager(BaseUserManager):
    def create_user(self, email, password=None, **kwargs):
        if not email:
            raise ValueError("Users must have a valid email address.")

        if not kwargs.get("username"):
            raise ValueError("Users must have a valid username.")

        account = self.model(
            email=self.normalize_email(email), username=kwargs.get("username")
        )

        account.set_password(password)
        account.save()

        return account

    def create_superuser(self, email, password, **kwargs):
        account = self.create_user(email, password, **kwargs)

        account.is_superuser = True
        account.is_staff = True
        account.save()

        return account


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(null=True, blank=True, unique=True)
    username = models.CharField(max_length=40, blank=True, null=True,default='')
    first_name = models.CharField(max_length=40, blank=True)
    last_name = models.CharField(max_length=40, blank=True)
    profile_image = models.ImageField(upload_to="profile_image", default="../static/assets/images/profile.jpg", null=True,  blank=True, verbose_name=_("Profile Image"))
    customer_id = models.CharField(_("Customer Id"), blank=True, max_length=255)
    language = models.CharField(max_length=40, blank=True)
    date_of_birth = models.DateField(blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    phone = models.CharField(max_length=15, blank=True)

    unique_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name=_("Unique Id"),)
    otp_expired_at = models.DateTimeField(blank=True, null=True)
    otp = models.CharField(max_length=5, blank=True, null=True)
    password_reset_link = models.UUIDField(unique=True, null=True, blank=True)
    email_verified = models.BooleanField(default=False)
    device = models.CharField(max_length=200, null=True, blank=True)

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = AccountManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    def __str__(self):
        return str(self.email) if self.email else str(self.device)

    def __unicode__(self):
        return self.email

    def get_full_name(self):
        return " ".join([self.first_name, self.last_name])

    def get_short_name(self):
        return self.first_name

    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"
        ordering = ["-created_at"]

    def get_absolute_url(self):
        return reverse("customadmin:user-list")



class PurchasedProduct(ActivityTracking):
    product = models.ForeignKey("ShopProduct", on_delete=models.CASCADE)
    product_price = models.FloatField(blank=True, null=True) 
    quantity = models.IntegerField(blank=True, null=True)
    user = models.ForeignKey("User", on_delete=models.CASCADE)
    total_amount = models.FloatField(blank=True, null=True)
    transaction_detail = models.ForeignKey("TransactionDetail", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.email}"

    class Meta:
        verbose_name = "Purchased Product"
        verbose_name_plural = "Purchased Products"
        ordering = ["-created_at"]


class BookedService(ActivityTracking):
    SERVICE_CHOICE = (
        ('Local', 'Local'),
        ('Overseas', 'Overseas'),
    )
    service = models.ForeignKey("Service", on_delete=models.CASCADE)
    booking_charge = models.FloatField(blank=True, null=True, default=50)
    user = models.ForeignKey("User", on_delete=models.CASCADE)
    service_date = models.DateField(blank=True, null=True)
    service_time = models.TimeField(blank=True, null=True)
    service_type = models.CharField(max_length=100, blank=True, null=True, default='', choices = SERVICE_CHOICE)
    transaction_detail = models.ForeignKey("TransactionDetail", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.email}"

    class Meta:
        verbose_name = "Booked Service"
        verbose_name_plural = "Booked Services"
        ordering = ["-created_at"]

app/customadmin/forms/category_image.py
# -*- coding: utf-8 -*-

from django import forms

from ..models import CategoryImage


# -----------------------------------------------------------------------------
# CategoryImage
# -----------------------------------------------------------------------------

class CategoryImageCreationForm(forms.ModelForm):
    """Custom CategoryImageCreationForm"""

    class Meta():
        model = CategoryImage
        fields = [
            "category_image",
            "service_category",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super(CategoryImageCreationForm, self).clean()
        category_image = cleaned_data.get("category_image")
        service_category = cleaned_data.get("service_category")

        if not category_image :
            raise forms.ValidationError(
                "Please add category image."
            )
        if not service_category :
            raise forms.ValidationError(
                "Please add service category."
            )
    def save(self, commit=True):
        instance = super().save(commit=False)
        cleaned_data = super(CategoryImageCreationForm, self).clean()

        if commit:
            instance.save()

        return instance


class CategoryImageChangeForm(forms.ModelForm):
    """Custom form to change CategoryImage"""

    class Meta():
        model = CategoryImage

        fields = [
            "category_image",
            "service_category",
        ]

    def clean(self):
        cleaned_data = super(CategoryImageChangeForm, self).clean()
        category_image = cleaned_data.get("category_image")
        service_category = cleaned_data.get("service_category")

        if not category_image :
            raise forms.ValidationError(
                "Please add category image."
            )
        if not service_category :
            raise forms.ValidationError(
                "Please service category."
            )

    def save(self, commit=True):
        instance = super().save(commit=False)

        if commit:
            instance.save()

        return instance

app/customadmin/forms/family_code.py
# -*- coding: utf-8 -*-

from django import forms

from ..models import FamilyCode


# -----------------------------------------------------------------------------
# FamilyCode
# -----------------------------------------------------------------------------

class FamilyCodeCreationForm(forms.ModelForm):
    """Custom FamilyCodeCreationForm"""

    class Meta():
        model = FamilyCode
        fields = [
            "code",
            "meaning"
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super(FamilyCodeCreationForm, self).clean()
        code = cleaned_data.get("code")
        meaning = cleaned_data.get("meaning")

        if not code :
            raise forms.ValidationError(
                "Please add code."
            )
        if not meaning :
            raise forms.ValidationError(
                "Please add meaning."
            )
    def save(self, commit=True):
        instance = super().save(commit=False)

        if commit:
            instance.save()

        return instance


class FamilyCodeChangeForm(forms.ModelForm):
    """Custom form to change FamilyCode"""

    class Meta():
        model = FamilyCode

        fields = [
            "code",
            "meaning"
        ]

    def clean(self):
        cleaned_data = super(FamilyCodeChangeForm, self).clean()
        code = cleaned_data.get("code")
        meaning = cleaned_data.get("meaning")

        if not code :
            raise forms.ValidationError(
                "Please add code."
            )
        if not meaning :
            raise forms.ValidationError(
                "Please add meaning."
            )

    def save(self, commit=True):
        instance = super().save(commit=False)

        if commit:
            instance.save()

        return instance

app/customadmin/forms/foundation_code.py
# -*- coding: utf-8 -*-

from django import forms

from ..models import FoundationCode


# -----------------------------------------------------------------------------
# FoundationCode
# -----------------------------------------------------------------------------

class FoundationCodeCreationForm(forms.ModelForm):
    """Custom FoundationCodeCreationForm"""

    class Meta():
        model = FoundationCode
        fields = [
            "code",
            "meaning"
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super(FoundationCodeCreationForm, self).clean()
        code = cleaned_data.get("code")
        meaning = cleaned_data.get("meaning")

        if not code :
            raise forms.ValidationError(
                "Please add code."
            )
        if not meaning :
            raise forms.ValidationError(
                "Please add meaning."
            )
    def save(self, commit=True):
        instance = super().save(commit=False)

        if commit:
            instance.save()

        return instance


class FoundationCodeChangeForm(forms.ModelForm):
    """Custom form to change FoundationCode"""

    class Meta():
        model = FoundationCode

        fields = [
            "code",
            "meaning"
        ]

    def clean(self):
        cleaned_data = super(FoundationCodeChangeForm, self).clean()
        code = cleaned_data.get("code")
        meaning = cleaned_data.get("meaning")

        if not code :
            raise forms.ValidationError(
                "Please add code."
            )
        if not meaning :
            raise forms.ValidationError(
                "Please add meaning."
            )

    def save(self, commit=True):
        instance = super().save(commit=False)

        if commit:
            instance.save()

        return instance

app/customadmin/forms/inquiry.py
# -*- coding: utf-8 -*-


from django import forms

from ..models import Inquiry, InquiryType
# -----------------------------------------------------------------------------
# Plans
# -----------------------------------------------------------------------------
class InquiryCreationForm(forms.ModelForm):
    """Custom InquiryCreationForm."""

    class Meta:
        model = Inquiry
        # fields = [
        #     "name",
        #     "email",
        #     "phone",
        #     "inquiry_type",
        #     "note"
        # ]
        fields="__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['inquiry_type'].required = False
        self.fields['note'].required = False

    def clean(self):
        cleaned_data = super(InquiryCreationForm, self).clean()
        name = cleaned_data.get("name")
        email = cleaned_data.get("email")
        phone = cleaned_data.get("phone")
        inquiry_type = cleaned_data.get("inquiry_type")

        if not name:
            raise forms.ValidationError(
                "Please enter name."
            )
        if not email:
            raise forms.ValidationError(
                "Please enter email."
            )
        if not phone:
            raise forms.ValidationError(
                "Please enter phone."
            )
        if not inquiry_type:
            raise forms.ValidationError(
                "Please enter inquiry_type."
            )

    def save(self, commit=True):
        instance = super().save(commit=False)
        if commit:
            instance.save()
        return instance



class InquiryChangeForm(forms.ModelForm):
    """Custom InquiryChangeForm."""
    class Meta:
        model = Inquiry
        fields = (
            "name",
            "email",
            "phone",
            "inquiry_type",
            "note"
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['inquiry_type'].required = False
        self.fields['note'].required = False

    def clean(self):
        cleaned_data = super(InquiryCreationForm, self).clean()
        name = cleaned_data.get("name")
        email = cleaned_data.get("email")
        phone = cleaned_data.get("phone")
        inquiry_type = cleaned_data.get("inquiry_type")

        if not name:
            raise forms.ValidationError(
                "Please enter name."
            )
        if not email:
            raise forms.ValidationError(
                "Please enter email."
            )
        if not phone:
            raise forms.ValidationError(
                "Please enter phone."
            )
        if not inquiry_type:
            raise forms.ValidationError(
                "Please enter inquiry_type."
            )

    def save(self, commit=True):
        instance = super().save(commit=False)
        if commit:
            instance.save()
        return instance

app/customadmin/forms/inquiry_type.py
# -*- coding: utf-8 -*-

from django import forms

from ..models import InquiryType

# -----------------------------------------------------------------------------
# Inquiry type
# -----------------------------------------------------------------------------

class InquiryTypeCreationForm(forms.ModelForm):
    """Custom InquiryTypeCreationForm"""

    class Meta():
        model = InquiryType
        fields = [
            "inquiry_type",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['inquiry_type'].required = False


    def clean(self):
        cleaned_data = super(InquiryTypeCreationForm, self).clean()
        inquiry_type = cleaned_data.get("inquiry_type")

        instance = InquiryType.objects.filter(inquiry_type__iexact=inquiry_type).first()
        if instance:
            raise forms.ValidationError(
                "Inquiry type already exists."
            )

        if not inquiry_type:
            raise forms.ValidationError(
                "Please add inquiry type."
            )

    def save(self, commit=True):
        instance = super().save(commit=False)

        if commit:
            instance.save()

        return instance


class InquiryTypeChangeForm(forms.ModelForm):
    """Custom form to change InquiryTypeChangeForm"""

    class Meta():
        model = InquiryType

        fields = [
            "inquiry_type",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['inquiry_type'].required = False

    def clean(self):
        cleaned_data = super(InquiryTypeChangeForm, self).clean()
        inquiry_type = cleaned_data.get("inquiry_type")

        if InquiryType.objects.filter(inquiry_type__iexact=inquiry_type).exclude(pk=self.instance.id).count() > 0:
            raise forms.ValidationError(
                "Inquiry type already exists."
            )
        if not inquiry_type:
            raise forms.ValidationError(
                "Please add Inquiry type."
            )

    def save(self, commit=True):
        instance = super().save(commit=False)

        if commit:
            instance.save()

        return instance

app/customadmin/templates/customadmin/adminuser/group_form.html
{% extends 'customadmin/change_form.html' %}
{% load static %}
{% load widget_tweaks %}
{% load admin_extras %}
{% load misc_filters %}
{% load crispy_forms_tags %}
{% load i18n %}


{% block page_content %}
    <form id="{{ opts.model_name }}-form" action="" method="post" enctype="multipart/form-data" autocomplete="off">

        {% include "customadmin/partials/form_hidden_fields.html" %}

        <div class="ibox float-e-margins">

            {% include "customadmin/partials/ibox_title.html" with ibox_title="Role Info" icon_class="fas fa-users" only %}

            <div class="ibox-content">

                <div class="row">
                    <div class="col-sm-6">
                        {{ form.name|as_crispy_field }}
                    </div>
                </div>

            </div>
            <!-- /ibox-content -->

        </div>
        <!-- /ibox -->

        <div class="ibox float-e-margins">

            {% include "customadmin/partials/ibox_title.html" with ibox_title="Permissions" icon_class="fas fa-key" only %}

            <div class="ibox-content">

                <div class="row">
                    <div class="col-sm-12">
                        {{ form.permissions|attr:"class:permissions-select"|attr:"size:10"|as_crispy_field }}
                        <small>Hold down "Control", or "Command" on a Mac, to select more than one.</small>
                    </div>
                </div>

            </div>
            <!-- /ibox-content -->

        </div>
        <!-- /ibox -->

        {% include "customadmin/partials/form_footer.html" %}

    </form>
{% endblock %}


{% block js %}
{{ block.super }}
<script src="{% static 'customadmin/js/userroles.js' %}"></script>

<script>
    $(function() {
        userroles.users.details();
    });
</script>
{% endblock %}

app/customadmin/templates/customadmin/adminuser/group_list.html
{% extends 'customadmin/change_list.html' %}
{% load static %}
{% load admin_extras %}
{% load misc_filters %}
{% load i18n %}


{% block page_content %}
    {% csrf_token %}

     {% include "customadmin/includes/list_header_card.html" with title="Create new roles" subtitle="Organize permissions for diffrent User roles." show_button=True %}

    <div class="ibox float-e-margins">
        {% comment %} <div class="ibox-title">
            <div class="ibox-tools">
                {% if has_add_permission %}
                <a href="{% url opts|admin_urlname:'create' %}" class="btn btn-primary btn-lg"><i class="fa fa-plus"></i> Add {{ opts.verbose_name|capfirst }}</a>
                {% endif %}
            </div>
        </div> {% endcomment %}

        <div class="ibox-content">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover" id="{{ opts.model_name }}-table">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <!-- <th>Modified</th> -->
                            <th></th>
                        </tr>
                    </thead>
                    <tfoot>
                            <tr>
                                <th>Name</th>
                                <!-- <th>Modified</th> -->
                                <th></th>
                            </tr>
                        </tfoot>
                    <tbody>
                        {% for o in object_list %}
                        <tr>
                            <td>{{ o.name }}</td>
                            <!-- <td>{{ o.modified }}</td> -->
                            <td class="row-actions">
                                {% include "customadmin/partials/list_row_actions.html" %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

{% block js %}
{{ block.super }}
<script src="{% static 'customadmin/js/userroles.js' %}"></script>

<script>
    {% comment %} var pagination_url = "{% url opts|admin_urlname:'list-ajax' %}"; {% endcomment %}
    $(function () {
        userroles.groups.index();
    });
</script>
{% endblock %}

app/customadmin/templates/customadmin/adminuser/password_change_form.html
{% extends 'customadmin/change_form.html' %}
{% load static %}
{% load widget_tweaks %}
{% load admin_extras %}
{% load misc_filters %}
{% load crispy_forms_tags %}
{% load i18n %}


{% block title %}
    Change Password
{% endblock%}


{% block page_header %}
    Change Password
{% endblock%}


{% block current_breadcrumb %}
<li class="breadcrumb-item">
    <a href="{% url 'customadmin:index' %}">{% trans 'Home' %}</a>
</li>
<li class="breadcrumb-item">
    <a href="{% url opts|admin_urlname:'list' %}">{{ opts.verbose_name_plural|capfirst }}</a>
</li>
<li class="breadcrumb-item">
    <a href="{% url opts|admin_urlname:'update' object.pk|admin_urlquote %}">{{ object|truncatewords:"18" }}</a>
</li>
<li class="breadcrumb-item">
    {% trans 'Change Password' %}
</li>
{% endblock %}


{% block formset_errors %}
    {% include "customadmin/partials/form_errors.html" with form=form %}
{% endblock%}


{% block page_content %}
    <form id="password-form" action="" method="post" enctype="multipart/form-data" autocomplete="off">

        {% include "customadmin/partials/form_hidden_fields.html" %}

        <div class="ibox float-e-margins">

            {% include "customadmin/partials/ibox_title.html" with ibox_title="Change Password" only %}

            <div class="ibox-content">

                <p>{% blocktrans with username=object %}Enter a new password for the user <strong>{{ username }}</strong>.{% endblocktrans %}</p>

                <div class="row">
                    <div class="col-sm-6">
                        {{ form.password1|as_crispy_field }}
                    </div>
                    <div class="col-sm-6">
                        {{ form.password2|as_crispy_field }}
                    </div>
                </div>

            </div>
            <!-- /ibox-content -->

        </div>
        <!-- /ibox -->

        <div class="modal-footer">
            <a href="javascript:history.back()" class="btn btn-white"><i class="fa fa-times"></i> Cancel</a>
            <button class="btn btn-primary" type="submit"><i class="fa fa-check"></i> Save</button>
        </div>

    </form>

{% endblock %}


{% block js %}
{{ block.super }}

<script>
    $(function() {
        // userroles.users.details();
    });
</script>
{% endblock %}

app/customadmin/templates/customadmin/adminuser/user_card_list.html
{% extends 'customadmin/change_list.html' %}
{% load static %}
{% load admin_extras %}
{% load misc_filters %}
{% load i18n %}


{% block page_content %}
    {% csrf_token %}

    

    {% include "customadmin/includes/list_header_card.html" with title="Create a new user card" subtitle="Create a new user card." show_button=True %}

    <div class="ibox float-e-margins">
        {% comment %} <div class="ibox-title">
            <div class="ibox-tools">
                {% if perms.users.add_user %}
                <a href="{% url opts|admin_urlname:'create' %}" class="btn btn-primary btn-lg"><i class="fa fa-plus"></i> Add {{ opts.verbose_name|capfirst }}</a>
                {% endif %}
            </div>
        </div> {% endcomment %}


        <div class="ibox-content">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover" id="{{ opts.model_name }}-table">
                    <thead>
                        <tr>
                            <th>User</th>
                            <th>Card Number</th>
                            <th>Expiry Month Year</th>
                            <th>Stripe Token</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>User</th>
                            <th>Card Number</th>
                            <th>Expiry Month Year</th>
                            <th>Stripe Token</th>
                            <th></th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for o in object_list %}
                        <tr>
                            <td>{{ o.user }}</td>
                            <td>{{ o.card_number }}</td>
                            <td>{{ o.expiry_month_year }}</td>
                            <td>{{ o.stripe_token }}</td>
                            <td class="row-actions">
                                {% include "customadmin/partials/list_row_actions.html" %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>

                </table>
            </div>
        </div>
    </div>

{% endblock %}


{% block js %}
{{ block.super }}
<script src="{% static 'customadmin/js/userroles.js' %}"></script>

<script>
    var pagination_url = "{% url opts|admin_urlname:'list-ajax' %}";
    $(function () {
        userroles.usercards.index();
    });
</script>
{% endblock %}

app/customadmin/templates/customadmin/adminuser/user_list.html
{% extends 'customadmin/change_list.html' %}
{% load static %}
{% load admin_extras %}
{% load misc_filters %}
{% load i18n %}


{% block page_content %}
    {% csrf_token %}



    {% include "customadmin/includes/list_header_card.html" with title="Create a new user" subtitle="Create a new user and assign with individual or group permissions." show_button=True %}

    <div class="ibox float-e-margins">
        {% comment %} <div class="ibox-title">
            <div class="ibox-tools">
                {% if perms.users.add_user %}
                <a href="{% url opts|admin_urlname:'create' %}" class="btn btn-primary btn-lg"><i class="fa fa-plus"></i> Add {{ opts.verbose_name|capfirst }}</a>
                {% endif %}
            </div>
        </div> {% endcomment %}


        <div class="ibox-content">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover" id="{{ opts.model_name }}-table">
                    <thead>
                        <tr>
                            <th>Email</th>
                            <th>Firstname</th>
                            <th>Lastname</th>
                            <th>Phone Number</th>
                            <th>Profile Image</th>
                            <th>Active</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Email</th>
                            <th>Firstname</th>
                            <th>Lastname</th>
                            <th>Phone Number</th>
                            <th>Profile Image</th>
                            <th>Active</th>
                            <th></th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for o in object_list %}
                        <tr>
                            <td>{{ o.email }}</td>
                            <td>{{ o.first_name }}</td>
                            <td>{{ o.last_name }}</td>
                            <td>{{ o.phone }}</td>
                            {% if o.profile_image %}
                            <td height="80px" width="180px"><img src="{{MEDIA_URL}}{{ o.profile_image.url }}" alt="no image" height="80x" width="180px"></td>
                            {% else %}
                            <td>No image</td>
                            {% endif %}
                            <td>{% show_check o.is_active %}</td>
                            <td class="row-actions">
                                {% include "customadmin/partials/list_row_more_actions.html" %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>

                </table>
            </div>
        </div>
    </div>

{% endblock %}


{% block js %}
{{ block.super }}
<script src="{% static 'customadmin/js/userroles.js' %}"></script>

<script>
    var pagination_url = "{% url opts|admin_urlname:'list-ajax' %}";
    $(function () {
        userroles.user.index();
    });
</script>
{% endblock %}